name: Playwright CI Workflow
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  verify-pull-request:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: 'CI'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run build

      - name: Run Linter
        run: npm run lint

      - name: Configure Environment
        env:
          CONFIG_ENV_NAME: 'CI'
          SITE_PASSWORD: 'secret_sauce'
        run: |
          touch .env
          echo "CONFIG_ENV_NAME=${CONFIG_ENV_NAME} SITE_PASSWORD=${SITE_PASSWORD}" | tr " " "\n" >> .env

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: allure-results
          retention-days: 20

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './allure-results'
          retention-days: 20
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  # deploy-test-results:
  #   needs: verify-pull-request
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/upload-artifact@master
  #       with:
  #         name: allure-results
  #         path: allure-results
  #         retention-days: 20

  #     - name: Get Allure history
  #       uses: actions/checkout@v3
  #       if: always()
  #       continue-on-error: true
  #       with:
  #         ref: gh-pages
  #         path: gh-pages
  #     # - name: Checkout
  #     #   uses: actions/checkout@v3
  #     - name: Setup Pages
  #       uses: actions/configure-pages@v2
  #     - name: Upload artifact
  #       uses: actions/upload-pages-artifact@v1
  #       with:
  #         # Upload entire repository
  #         path: './allure-history'
  #         retention-days: 20
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v1

  # - name: Test marketplace action
  #   uses: simple-elf/allure-report-action@master
  #   if: always()
  #   id: allure-report
  #   with:
  #     allure_results: allure-results
  #     gh_pages: gh-pages
  #     allure_report: allure-report
  #     allure_history: allure-history
  #     keep_reports: 20

  # - name: Deploy report to Github Pages
  # if: always()
  # uses: peaceiris/actions-gh-pages@v2
  # env:
  #   PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   PUBLISH_BRANCH: gh-pages
  #   PUBLISH_DIR: allure-history
