name: Playwright CI Workflow
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  verify-pull-request:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: 'DEV'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run build

      - name: Run Linter
        run: npm run lint

      - name: Configure Environment
        env:
          CONFIG_ENV_NAME: 'DEV'
        run: |
          touch .env
          echo "CONFIG_ENV_NAME=${CONFIG_ENV_NAME}" | tr " " "\n" >> .env

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: allure-results
          retention-days: 20

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
    
      - name: Post the link to the report
        id: report-link
        if: always()
        run: |
          url-link=https://guzikowski.github.io/Playwright_E2E_API_Calls/${{ github.run_number }}
          echo "REPORT_LINK=$url-link" >> $GITHUB_OUTPUT
        
    outputs:
      test-report-link: ${{steps.report-link.outputs.REPORT_LINK}}
      
  test-report:
    if: always()
    runs-on: ubuntu-latest
    needs: verify-pull-request
    steps:
      - run: echo "${{needs.jobs.outputs.test-report-link}}"
        
